POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json

{
    "username": "silvia",
    "password": "1234"
}

###
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "username": "silva",
    "password": "1244"
}

###
GET http://localhost:3000/protected HTTP/1.1
Cookie: connect.sid=s%3A9tz6SFO7DO2Iab8ceg-gzq7JkNQXTKQV.2EWlbtWIpRB4obqT87ZoSaBSbltMkFVAzaiRDwbo45Y